/** Auto-generated by scripts/generate-legal-content.mjs */

import * as termsOfService from "./terms-of-service";
import * as privacyPolicy from "./privacy-policy";
import * as refundPolicy from "./refund-policy";
import * as copyright from "./copyright";
import * as servicePaymentGuide from "./service-payment-guide";

export const LEGAL_DOCUMENTS = {
  "terms-of-service": {
    slug: "terms-of-service",
    title: termsOfService.title,
    articleHtml: termsOfService.articleHtml,
  },
  "privacy-policy": {
    slug: "privacy-policy",
    title: privacyPolicy.title,
    articleHtml: privacyPolicy.articleHtml,
  },
  "refund-policy": {
    slug: "refund-policy",
    title: refundPolicy.title,
    articleHtml: refundPolicy.articleHtml,
  },
  copyright: {
    slug: "copyright",
    title: copyright.title,
    articleHtml: copyright.articleHtml,
  },
  "service-payment-guide": {
    slug: "service-payment-guide",
    title: servicePaymentGuide.title,
    articleHtml: servicePaymentGuide.articleHtml,
  },
} as const;

export type LegalSlug = keyof typeof LEGAL_DOCUMENTS;
export const LEGAL_SLUGS = Object.keys(LEGAL_DOCUMENTS) as LegalSlug[];
